os: osx
sudo: false
language: go

env: GO111MODULE=on
go:
  - 1.13.x

script:
  - DMG_FILE=PagerdutyNotifier.dmg
  - make install
  - make build
  - make dmg PACKAGE=${DMG_FILE}

branches:
  only: master

before_deploy:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d-%H%M')}
- git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: ${DMG_FILE}
  skip_cleanup: true